# Generated by Django 5.2.12 on 2026-04-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sociallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutprofile',
            old_name='one_line_practice_description',
            new_name='one_line_bio',
        ),
        migrations.RenameField(
            model_name='aboutprofile',
            old_name='practice_structure',
            new_name='professional_context',
        ),
        migrations.RenameField(
            model_name='aboutprofile',
            old_name='practice_summary',
            new_name='bio_summary',
        ),
        migrations.RenameField(
            model_name='aboutprofile',
            old_name='project_leadership',
            new_name='work_approach',
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='professional_context',
            field=models.CharField(blank=True, help_text="A short truthful descriptor such as 'Solo practitioner' or 'Small studio'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='bio_summary',
            field=models.TextField(blank=True, help_text='Short factual summary of who you are, where you are based, and the kind of work you do.'),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='work_approach',
            field=models.TextField(blank=True, help_text='Explain how you work and how collaborators or consultants are involved.'),
        ),
    ]
