# Generated by Django 5.2.12 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sitesettings_hero_compact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blog_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Show the optional Blog section in public navigation.',
            ),
        ),
    ]
