# Generated by Django 5.2.12 on 2026-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_services_testimonials_enabled_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='website_domain',
            field=models.CharField(blank=True, help_text='Live domain for this deployment, e.g. mystudio.com', max_length=200),
        ),
    ]
