# Generated by Django 5.2.12 on 2026-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('who_for', models.CharField(blank=True, max_length=250)),
                ('value_proposition', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True, help_text='One deliverable per line.')),
                ('icon_name', models.CharField(blank=True, help_text="Optional icon identifier (e.g. 'pen-ruler', 'building').", max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
