# Generated by Django 5.2.12 on 2026-04-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Short description shown in listings. Keep under 200 characters.', max_length=300)),
                ('body', models.TextField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags, e.g. 'design, process, tools'.", max_length=200)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_date', 'title'],
            },
        ),
    ]
