# Generated by Django 5.2.12 on 2026-03-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_product_quality_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_description',
            field=models.CharField(blank=True, help_text='Meta description for the About page. Keep under 160 characters.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_meta_description',
            field=models.CharField(blank=True, help_text='Meta description for the Contact page. Keep under 160 characters.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_meta_description',
            field=models.CharField(blank=True, help_text='Meta description for the Projects list page. Keep under 160 characters.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_meta_description',
            field=models.CharField(blank=True, help_text='Meta description for the Services page. Keep under 160 characters.', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Recommended: at least 1600 × 900 px, JPEG or WebP. Used as the hero image and OpenGraph share image.', null=True, upload_to='projects/covers/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='process',
            field=models.TextField(blank=True, help_text='Optional — describe the design and construction process, methods used, or team collaboration.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Overrides short description in search results. Under 160 characters.', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Overrides project title in browser tab and search results. Ideal length: under 60 characters.', max_length=70),
        ),
        migrations.AlterField(
            model_name='project',
            name='services_provided',
            field=models.TextField(blank=True, help_text="Scope of services delivered, e.g. 'Concept design through construction administration.' One service per line."),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='One or two clear sentences shown on project cards and in search results. Under 160 characters is ideal.', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='GA4 Measurement ID, e.g. G-XXXXXXXXXX.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Default meta description (homepage and fallback). Keep under 160 characters.', max_length=160),
        ),
    ]
